name: Call a reusable workflow 


on:
 push:
    branches:
    - main
    - release/*

jobs:
  call-resuable-workflow:
   uses: sanknoorsachin/reusable-workflow/blob/main/.github/workflows/reusable.yml@main
   

