on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Test Actions Demo
        uses: sanknoorsachin/actions-demo@v4
        with:
          who-to-greet: 'This is action demo'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
