name: Test endpoint 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : zip files
      run : |
       zip -r /home/runner/work/${{ github.event.repository.name }}  /home/runner/work/${{ github.event.repository.name }}
       sudo ls -l *.java | /home/runner/work/${{ github.event.repository.name }} -l
  
    - name: REST API with curl
      env:
        filename : "/home/runner/work/exchange-rate-service.zip"
      run: |
       curl -H "Content-Type: multipart/form-data" -F "file=@/home/runner/work/${{ github.event.repository.name }}.zip" http://192.168.1.105:8080/api/upload
