name: Test endpoint 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : zip files
      run : |
       zip -r /home/runner/work/exchange-rate-service  /home/runner/work/exchange-rate-service/exchange-rate-service
       
    
    - name: REST API with curl
      run: |
        curl -X GET "https://api.restful-api.dev/objects"

