name: Test endpoint 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name : zip files
      env: 
        md: false
      run : |
       echo ${{ github.event.repository.name }}
       zip -r /home/runner/work/${{ github.event.repository.name }}  /home/runner/work/${{ github.event.repository.name }}
       
     
       - name: Read README.md(gh-pages)
         id: ghpages
         uses: jaywcjlove/github-action-read-file@main
         with:
       path: README.md
    - name: Echo README.md(gh-pages)
      run: echo "${{ steps.ghpages.outputs.content }}"
      
    - name: REST API with curl
      env:
        filename : $md
      run: |
       echo {{ md }}
       curl -H "Content-Type: multipart/form-data" -F "file=@/home/runner/work/${{ github.event.repository.name }}.zip" -F "isMarkDown=$filename" http://192.168.1.105:8080/api/upload
